<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Christophe Duquesne (DRYADE SA) -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:webTopo="http://soap.webtopo"
             xmlns:topo="http://xsd.webtopo"
             targetNamespace="http://soap.webtopo">
    <import namespace="http://xsd.webtopo" location="webtopo.xsd"/>
    <message name="TopologyRequest">
        <part name="RequestPart" element="topo:TopologyRequest"/>
    </message>
    <message name="TopologyResponse">
        <part name="ResponsePart" element="topo:TopologyResponse"/>
    </message>
    <portType name="SOAP-Port">
        <operation name="Topology">
            <input message="webTopo:TopologyRequest" name="TopologyRequest"/>                           
            <output message="webTopo:TopologyResponse" name="TopologyResponse"/>
        </operation>
    </portType>
    <binding name="webTopoSOAPBinding" type="webTopo:SOAP-Port">
        <operation name="Topology">
            <soap:operation soapAction="RequestTopology"/>
            <input name="TopologyRequest">
                <soap:body use="literal"/>
            </input>
            <output name="TopologyResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="WebTopo">
        <port binding="webTopo:webTopoSOAPBinding" name="TopologyResourcePort">          
            <soap:address location="http://localhost:8080/server/"/>             
        </port>
    </service>
</definitions>